services:
    dev:
        container_name: dev
        extends:
            file: $PWD/docker/compose_fragments/service_base.yml
            service: base
        image: dev-image
        build:
            context: $PWD/
            dockerfile: $PWD/docker/dev.Dockerfile
        volumes:
            - $PWD/scripts:/usr/bin/app/scripts
            - $PWD/generated:/usr/bin/app/generated
            - $PWD/src:/usr/bin/app/src
            - $PWD/.env:/usr/bin/app/.env
            - $PWD/tsconfig.json:/usr/bin/app/tsconfig.json
        command: yarn dev

    prod:
        container_name: prod
        extends:
            file: $PWD/docker/compose_fragments/service_base.yml
            service: base
        image: prod-image
        build:
            context: $PWD/
            dockerfile: $PWD/docker/prod.Dockerfile
        command: yarn start
